<?php
/**
 * Redux Settings
 *
 * @package OlyveTheme
 * @version 1.0.0
 */
// Exit if accessed directly
defined( 'ABSPATH' ) || exit;

Redux::set_section(
	$opt_name,
	array(
		'title'      => esc_html__( 'Footer Typography', 'olyve' ),
		'id'         => 'olyve_footer_typography_settings',
        'icon'       => 'dashicons dashicons-arrow-right-alt',
		'subsection' => true,
		'fields'     => array(
            array(
				'id'                => 'olyve_footer_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap' ),
			),
            array(
				'id'       => 'olyve_footer_link',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Link Color', 'olyve' ),
                'active'   => false, 
				'output'   => array( '.dtr-footer-section-wrap a' ),
			),
            // h1
            array(
				'id'    => 'olyve_info_footer_headings',
				'type'  => 'info',
                'title' => esc_html__( 'Headings in Footer', 'olyve' ),
			),  
            array(
				'id'                => 'olyve_footer_h1_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H1', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h1' ),
			),
            array(
				'id'                => 'olyve_footer_h2_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H2', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h2' ),
			),
            array(
				'id'                => 'olyve_footer_h3_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H3', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h3' ),
			),
            array(
				'id'                => 'olyve_footer_h4_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H4', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h4' ),
			),
            array(
				'id'                => 'olyve_footer_h5_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H5', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h5' ),
			),
            array(
				'id'                => 'olyve_footer_h6_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'H6', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => true,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap h6' ),
			),
            array(
				'id'   => 'olyve_info_copyright_typo',
				'type' => 'info',
                'title' => esc_html__( 'Copyright', 'olyve' ),
			),
            array(
				'id'                => 'olyve_copyright_typo',
				'type'              => 'typography',
				'title'             => esc_html__( 'Font', 'olyve' ),
				'google'            => true,
                'font-backup'       => true,
                'all-styles'        => true,
				'all-subsets'       => true,
                'text-align'        => false,
				'letter-spacing'    => true, 
                'font-size'         => true,
                'line-height'       => true,
                'units'             => 'px',
				'output'            => array( '.dtr-footer-section-wrap .dtr-copyright' ),
			),
            array(
				'id'       => 'olyve_copyright_link',
				'type'     => 'link_color',
                'title'    => esc_html__( 'Link Color', 'olyve' ),
                'active'   => false, 
				'output'   => array( '.dtr-footer-section-wrap .dtr-copyright a' ),
			),
		),
	)
);